<?php
/**
 * Module 7: AI content generation, Phase 5.
 *
 * @package MCPSuite\Modules
 */

declare( strict_types = 1 );

namespace MCPSuite\Modules;

use MCPSuite\Core\AuditLogger;
use MCPSuite\Core\Capabilities;
use MCPSuite\Core\FeatureFlags;
use MCPSuite\Modules\AiWriting\AiRunRepository;
use MCPSuite\Modules\AiWriting\AiRunStatus;
use MCPSuite\Modules\AiWriting\AiWritingRestController;
use MCPSuite\Modules\AiWriting\InvalidStatusTransitionException;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class AiWritingModule extends AbstractModule {

	private const NONCE_ACTION = 'mcp_suite_ai_review_action';
	private const NONCE_FIELD  = 'mcp_suite_ai_review_nonce';

	public function key(): string {
		return FeatureFlags::MODULE_AI_WRITING;
	}

	public function label(): string {
		return __( 'AI Writing Queue', 'wp-mcp-suite' );
	}

	public function required_capability(): string {
		return Capabilities::MANAGE_AI_CONTENT;
	}

	protected function roadmap_description(): string {
		return __( 'Not applicable — this module is implemented.', 'wp-mcp-suite' );
	}

	public function register(): void {
		add_action( 'mcp_suite_cron_ai_queue_check', array( $this, 'run_stale_review_check' ) );

		if ( ! wp_next_scheduled( 'mcp_suite_cron_ai_queue_check' ) ) {
			wp_schedule_event( time(), 'hourly', 'mcp_suite_cron_ai_queue_check' );
		}

		add_action(
			'rest_api_init',
			static function (): void {
				( new AiWritingRestController() )->register_routes();
			}
		);

		// The actual, structural enforcement of the mandatory review gate:
		// runs on every post save, before it hits the database, and
		// re-writes an attempted "publish" back to "draft" for any post
		// tracked in wp_mcp_ai_runs that has not been human-reviewed —
		// regardless of whether the publish attempt came through this
		// module's own REST route, the normal block editor, quick-edit, or
		// any other plugin. This is what makes the rule "enforced in code,"
		// not just "the built-in UI happens to ask for review first."
		add_filter( 'wp_insert_post_data', array( $this, 'block_unreviewed_ai_publish' ), 10, 2 );

		add_action( 'admin_post_mcp_suite_ai_approve', array( $this, 'handle_approve_form' ) );
		add_action( 'admin_post_mcp_suite_ai_reject', array( $this, 'handle_reject_form' ) );
		add_action( 'admin_notices', array( $this, 'render_blocked_publish_notice' ) );
	}

	/**
	 * @param array<string,mixed> $data
	 * @param array<string,mixed> $postarr
	 * @return array<string,mixed>
	 */
	public function block_unreviewed_ai_publish( array $data, array $postarr ): array {
		if ( 'publish' !== ( $data['post_status'] ?? '' ) ) {
			return $data;
		}

		$post_id = (int) ( $postarr['ID'] ?? 0 );
		if ( 0 === $post_id ) {
			return $data; // brand-new post being created directly as published — never an AI-generated draft, which this module always creates as 'draft' first
		}

		$run = ( new AiRunRepository() )->find_by_post_id( $post_id );

		if ( null === $run || AiRunStatus::PUBLISHED === $run->status ) {
			return $data; // not AI-tracked, or already legitimately approved by handle_approve()
		}

		if ( ! $run->human_reviewed ) {
			$data['post_status'] = 'draft';

			set_transient( 'mcp_suite_ai_blocked_publish_' . get_current_user_id(), $post_id, 60 );

			AuditLogger::log(
				AuditLogger::ACTION_PERMISSION_DENIED,
				'ai_writing',
				'post',
				$post_id,
				false,
				array( 'reason' => 'attempted to publish an AI-drafted post without going through the review/approve action' )
			);
		}

		return $data;
	}

	public function render_blocked_publish_notice(): void {
		$key     = 'mcp_suite_ai_blocked_publish_' . get_current_user_id();
		$post_id = get_transient( $key );

		if ( ! $post_id ) {
			return;
		}

		delete_transient( $key );

		echo '<div class="notice notice-warning"><p>' .
			esc_html__( 'This post was generated by the AI Writing Queue and has not been marked as human-reviewed yet, so it was kept as a draft instead of being published. Use "Approve & Publish" on the AI Writing Queue screen once you have reviewed it.', 'wp-mcp-suite' ) .
			' <a href="' . esc_url( admin_url( 'admin.php?page=mcp-suite-ai_writing' ) ) . '">' . esc_html__( 'Go to AI Writing Queue', 'wp-mcp-suite' ) . '</a></p></div>';
	}

	public function handle_approve_form(): void {
		$this->verify_form_request();

		$run_id     = isset( $_POST['run_id'] ) ? absint( $_POST['run_id'] ) : 0;
		$repository = new AiRunRepository();
		$run        = $repository->find( $run_id );

		if ( null !== $run ) {
			try {
				$repository->approve_and_publish( $run_id, get_current_user_id() );
				if ( null !== $run->post_id ) {
					wp_update_post( array( 'ID' => $run->post_id, 'post_status' => 'publish' ) );
				}
				AuditLogger::log( AuditLogger::ACTION_EDIT, 'ai_writing', 'post', $run->post_id, true, array( 'event' => 'ai_run_approved_and_published', 'run_id' => $run_id ) );
			} catch ( InvalidStatusTransitionException $e ) {
				// Fall through to redirect; nothing destructive happened.
			}
		}

		wp_safe_redirect( admin_url( 'admin.php?page=mcp-suite-ai_writing' ) );
		exit;
	}

	public function handle_reject_form(): void {
		$this->verify_form_request();

		$run_id     = isset( $_POST['run_id'] ) ? absint( $_POST['run_id'] ) : 0;
		$repository = new AiRunRepository();
		$run        = $repository->find( $run_id );

		if ( null !== $run ) {
			try {
				$repository->reject( $run_id, get_current_user_id() );
				if ( null !== $run->post_id ) {
					wp_trash_post( $run->post_id );
				}
				AuditLogger::log( AuditLogger::ACTION_EDIT, 'ai_writing', 'post', $run->post_id, true, array( 'event' => 'ai_run_rejected', 'run_id' => $run_id ) );
			} catch ( InvalidStatusTransitionException $e ) {
				// Fall through to redirect.
			}
		}

		wp_safe_redirect( admin_url( 'admin.php?page=mcp-suite-ai_writing' ) );
		exit;
	}

	private function verify_form_request(): void {
		if ( ! isset( $_POST[ self::NONCE_FIELD ] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST[ self::NONCE_FIELD ] ) ), self::NONCE_ACTION ) ) {
			wp_die( esc_html__( 'Security check failed. Please go back and try again.', 'wp-mcp-suite' ) );
		}

		if ( ! current_user_can( Capabilities::MANAGE_AI_CONTENT ) ) {
			wp_die( esc_html__( 'You do not have permission to do that.', 'wp-mcp-suite' ) );
		}
	}

	/**
	 * Hourly cron. Generation itself is synchronous (an OpenAI-compatible
	 * chat-completions call is a single request/response, not a
	 * long-running job — see PHASE5-NOTES.md for why this isn't a
	 * generate-side queue), so this tick's real job is surfacing drafts
	 * that have been waiting for review too long, via the audit log —
	 * a genuinely useful signal rather than a no-op cron kept only to
	 * match the spec's literal cron list.
	 */
	public function run_stale_review_check(): void {
		if ( ! FeatureFlags::is_enabled( FeatureFlags::MODULE_AI_WRITING ) ) {
			return;
		}

		$pending = ( new AiRunRepository() )->find_pending_review( 100 );

		if ( array() !== $pending ) {
			AuditLogger::log( AuditLogger::ACTION_VIEW, 'ai_writing', 'pending_review_summary', null, true, array( 'pending_count' => count( $pending ) ) );
		}
	}

	public function render_admin_page(): void {
		if ( ! current_user_can( $this->required_capability() ) ) {
			wp_die( esc_html__( 'You do not have permission to view this page.', 'wp-mcp-suite' ) );
		}

		AuditLogger::log( AuditLogger::ACTION_VIEW, 'ai_writing', 'admin_page' );

		$configured = null !== ( new \MCPSuite\Modules\AiWriting\AiProviderCredentialsRepository() )->get();

		echo '<div class="wrap mcp-suite-module-page"><h1>' . esc_html( $this->label() ) . '</h1>';

		if ( ! $configured ) {
			echo '<div class="notice notice-warning"><p>' .
				esc_html__( 'No AI provider is configured yet.', 'wp-mcp-suite' ) . ' ' .
				'<a href="' . esc_url( admin_url( 'admin.php?page=mcp-suite-settings' ) ) . '">' . esc_html__( 'Set it up on the Settings screen.', 'wp-mcp-suite' ) . '</a></p></div>';
		}

		echo '<p>' . esc_html__( 'Every AI-generated draft requires an explicit Approve action here before it can be published — publishing it directly through the normal editor will be reverted back to draft.', 'wp-mcp-suite' ) . '</p>';

		$pending = ( new AiRunRepository() )->find_pending_review();

		echo '<h2>' . esc_html__( 'Pending Review', 'wp-mcp-suite' ) . '</h2>';
		echo '<table class="widefat striped"><thead><tr><th>' . esc_html__( 'Draft', 'wp-mcp-suite' ) . '</th><th>' . esc_html__( 'Provider / Model', 'wp-mcp-suite' ) . '</th><th>' . esc_html__( 'Actions', 'wp-mcp-suite' ) . '</th></tr></thead><tbody>';

		if ( empty( $pending ) ) {
			echo '<tr><td colspan="3">' . esc_html__( 'Nothing pending review.', 'wp-mcp-suite' ) . '</td></tr>';
		} else {
			foreach ( $pending as $run ) {
				$title = $run->post_id ? ( get_the_title( $run->post_id ) ?: '#' . $run->post_id ) : '—';
				$edit_link = $run->post_id ? get_edit_post_link( $run->post_id ) : '';

				echo '<tr><td>' . ( $edit_link ? '<a href="' . esc_url( $edit_link ) . '">' . esc_html( $title ) . '</a>' : esc_html( $title ) ) . '</td>' .
					'<td>' . esc_html( $run->provider . ' / ' . $run->model ) . '</td><td>';

				echo '<form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '" style="display:inline">';
				wp_nonce_field( self::NONCE_ACTION, self::NONCE_FIELD );
				echo '<input type="hidden" name="action" value="mcp_suite_ai_approve">';
				echo '<input type="hidden" name="run_id" value="' . esc_attr( (string) $run->id ) . '">';
				submit_button( __( 'Approve & Publish', 'wp-mcp-suite' ), 'primary', '', false );
				echo '</form> ';

				echo '<form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '" style="display:inline">';
				wp_nonce_field( self::NONCE_ACTION, self::NONCE_FIELD );
				echo '<input type="hidden" name="action" value="mcp_suite_ai_reject">';
				echo '<input type="hidden" name="run_id" value="' . esc_attr( (string) $run->id ) . '">';
				submit_button( __( 'Reject', 'wp-mcp-suite' ), 'secondary', '', false );
				echo '</form>';

				echo '</td></tr>';
			}
		}

		echo '</tbody></table></div>';
	}
}
